config_name: phase1_4way_36_full
question_text: Which response sounds most appropriate to the context?
eval_items:
  - id: 1
    context_path: audio/1b_patti.m4a
    agent_paths:
      - audio/1B_JustinM_output1.wav
      - audio/1B_JustinBF_output1.wav
      - audio/1B_JustinS_output1.wav
      - audio/1B_JustinZM_output1.wav
  - id: 2
    context_path: audio/1b_patti.m4a
    agent_paths:
      - audio/1B_JustinM_output2.wav
      - audio/1B_JustinBF_output2.wav
      - audio/1B_JustinS_output2.wav
      - audio/1B_JustinZM_output2.wav
  - id: 3
    context_path: audio/1b_patti.m4a
    agent_paths:
      - audio/1B_JustinM_output3.wav
      - audio/1B_JustinBF_output3.wav
      - audio/1B_JustinS_output3.wav
      - audio/1B_JustinZM_output3.wav
  - id: 4
    context_path: audio/1b_patti.m4a
    agent_paths:
      - audio/1B_SherrinM_output1.wav
      - audio/1B_SherrinBF_output1.wav
      - audio/1B_SherrinS_output1.wav
      - audio/1B_SherrinZM_output1.wav
  - id: 5
    context_path: audio/1b_patti.m4a
    agent_paths:
      - audio/1B_SherrinM_output2.wav
      - audio/1B_SherrinBF_output2.wav
      - audio/1B_SherrinS_output2.wav
      - audio/1B_SherrinZM_output2.wav
  - id: 6
    context_path: audio/1b_patti.m4a
    agent_paths:
      - audio/1B_SherrinM_output3.wav
      - audio/1B_SherrinBF_output3.wav
      - audio/1B_SherrinS_output3.wav
      - audio/1B_SherrinZM_output3.wav
  - id: 7
    context_path: audio/1b_patti.m4a
    agent_paths:
      - audio/1B_EricaM_output1.wav
      - audio/1B_EricaBF_output1.wav
      - audio/1B_EricaS_output1.wav
      - audio/1B_EricaZM_output1.wav
  - id: 8
    context_path: audio/1b_patti.m4a
    agent_paths:
      - audio/1B_EricaM_output2.wav
      - audio/1B_EricaBF_output2.wav
      - audio/1B_EricaS_output2.wav
      - audio/1B_EricaZM_output2.wav
  - id: 9
    context_path: audio/1b_patti.m4a
    agent_paths:
      - audio/1B_EricaM_output3.wav
      - audio/1B_EricaBF_output3.wav
      - audio/1B_EricaS_output3.wav
      - audio/1B_EricaZM_output3.wav
  - id: 10
    context_path: audio/1c_rachel.m4a
    agent_paths:
      - audio/1C_JustinM_output1.wav
      - audio/1C_JustinBF_output1.wav
      - audio/1C_JustinS_output1.wav
      - audio/1C_JustinZM_output1.wav
  - id: 11
    context_path: audio/1c_rachel.m4a
    agent_paths:
      - audio/1C_JustinM_output2.wav
      - audio/1C_JustinBF_output2.wav
      - audio/1C_JustinS_output2.wav
      - audio/1C_JustinZM_output2.wav
  - id: 12
    context_path: audio/1c_rachel.m4a
    agent_paths:
      - audio/1C_JustinM_output3.wav
      - audio/1C_JustinBF_output3.wav
      - audio/1C_JustinS_output3.wav
      - audio/1C_JustinZM_output3.wav
  - id: 13
    context_path: audio/1c_rachel.m4a
    agent_paths:
      - audio/1C_SherrinM_output1.wav
      - audio/1C_SherrinBF_output1.wav
      - audio/1C_SherrinS_output1.wav
      - audio/1C_SherrinZM_output1.wav
  - id: 14
    context_path: audio/1c_rachel.m4a
    agent_paths:
      - audio/1C_SherrinM_output2.wav
      - audio/1C_SherrinBF_output2.wav
      - audio/1c_SherrinS_output2.wav
      - audio/1C_SherrinZM_output2.wav
  - id: 15
    context_path: audio/1c_rachel.m4a
    agent_paths:
      - audio/1C_SherrinM_output3.wav
      - audio/1C_SherrinBF_output3.wav
      - audio/1C_SherrinS_output3.wav
      - audio/1C_SherrinZM_output3.wav
  - id: 16
    context_path: audio/1c_rachel.m4a
    agent_paths:
      - audio/1C_EricaM_output1.wav
      - audio/1C_EricaBF_output1.wav
      - audio/1C_EricaS_output1.wav
      - audio/1C_EricaZM_output1.wav
  - id: 17
    context_path: audio/1c_rachel.m4a
    agent_paths:
      - audio/1C_EricaM_output2.wav
      - audio/1C_EricaBF_output2.wav
      - audio/1C_EricaS_output2.wav
      - audio/1C_EricaZM_output2.wav
  - id: 18
    context_path: audio/1c_rachel.m4a
    agent_paths:
      - audio/1C_EricaM_output3.wav
      - audio/1C_EricaBF_output3.wav
      - audio/1C_EricaS_output3.wav
      - audio/1C_EricaZM_output3.wav
  - id: 19
    context_path: audio/1d_patti.m4a
    agent_paths:
      - audio/1D_JustinM_output1.wav
      - audio/1D_JustinBF_output1.wav
      - audio/1D_JustinS_output1.wav
      - audio/1D_JustinZM_output1.wav
  - id: 20
    context_path: audio/1d_patti.m4a
    agent_paths:
      - audio/1D_JustinM_output2.wav
      - audio/1D_JustinBF_output2.wav
      - audio/1D_JustinS_output2.wav
      - audio/1D_JustinZM_output2.wav
  - id: 21
    context_path: audio/1d_patti.m4a
    agent_paths:
      - audio/1D_JustinM_output3.wav
      - audio/1D_JustinBF_output3.wav
      - audio/1D_JustinS_output3.wav
      - audio/1D_JustinZM_output3.wav
  - id: 22
    context_path: audio/1d_patti.m4a
    agent_paths:
      - audio/1D_SherrinM_output1.wav
      - audio/1D_SherrinBF_output1.wav
      - audio/1D_SherrinS_output1.wav
      - audio/1D_SherrinZM_output1.wav
  - id: 23
    context_path: audio/1d_patti.m4a
    agent_paths:
      - audio/1D_SherrinM_output2.wav
      - audio/1D_SherrrinBF_output2.wav
      - audio/1D_SherrinS_output2.wav
      - audio/1D_SherrinZM_output2.wav
  - id: 24
    context_path: audio/1d_patti.m4a
    agent_paths:
      - audio/1D_SherrinM_output3.wav
      - audio/1D_SherrinBF_output3.wav
      - audio/1D_SherrinS_output3.wav
      - audio/1D_SherrinZM_output3.wav
  - id: 25
    context_path: audio/1d_patti.m4a
    agent_paths:
      - audio/1D_EricaM_output1.wav
      - audio/1D_EricaBF_output1.wav
      - audio/1D_EricaS_output1.wav
      - audio/1D_EricaZM_output1.wav
  - id: 26
    context_path: audio/1d_patti.m4a
    agent_paths:
      - audio/1D_EricaM_output2.wav
      - audio/1D_EricaBF_output2.wav
      - audio/1D_EricaS_output2.wav
      - audio/1D_EricaZM_output2.wav
  - id: 27
    context_path: audio/1d_patti.m4a
    agent_paths:
      - audio/1D_EricaM_output3.wav
      - audio/1D_EricaBF_output3.wav
      - audio/1D_EricaS_output3.wav
      - audio/1D_EricaZM_output3.wav
  - id: 28
    context_path: audio/2b_rachel.m4a
    agent_paths:
      - audio/2B_JustinM_output1.wav
      - audio/2B_JustinBF_output1.wav
      - audio/2B_JustinS_output1.wav
      - audio/2B_JustinZM_output1.wav
  - id: 29
    context_path: audio/2b_rachel.m4a
    agent_paths:
      - audio/2B_JustinM_output2.wav
      - audio/2B_JustinBF_output2.wav
      - audio/2B_JustinS_output2.wav
      - audio/2B_JustinZM_output2.wav
  - id: 30
    context_path: audio/2b_rachel.m4a
    agent_paths:
      - audio/2B_JustinM_output3.wav
      - audio/2B_JustinBF_output3.wav
      - audio/2B_JustinS_output3.wav
      - audio/2B_JustinZM_output3.wav
  - id: 31
    context_path: audio/2b_rachel.m4a
    agent_paths:
      - audio/2B_SherrinM_output1.wav
      - audio/2B_SherrinBF_output1.wav
      - audio/2B_SherrinS_output1.wav
      - audio/2B_SherrinZM_output1.wav
  - id: 32
    context_path: audio/2b_rachel.m4a
    agent_paths:
      - audio/2B_SherrinM_output2.wav
      - audio/2B_SherrinBF_output2.wav
      - audio/2B_SherrinS_output2.wav
      - audio/2B_SherrinZM_output2.wav
  - id: 33
    context_path: audio/2b_rachel.m4a
    agent_paths:
      - audio/2B_SherrinM_output3.wav
      - audio/2B_SherrinBF_output3.wav
      - audio/2B_SherrinS_output3.wav
      - audio/2B_SherrinZM_output3.wav
  - id: 34
    context_path: audio/2b_rachel.m4a
    agent_paths:
      - audio/2B_EricaM_output1.wav
      - audio/2B_EricaBF_output1.wav
      - audio/2B_EricaS_output1.wav
      - audio/2B_EricaZM_output1.wav
  - id: 35
    context_path: audio/2b_rachel.m4a
    agent_paths:
      - audio/2B_EricaM_output2.wav
      - audio/2B_EricaBF_output2.wav
      - audio/2B_EricaS_output2.wav
      - audio/2B_EricaZM_output2.wav
  - id: 36
    context_path: audio/2b_rachel.m4a
    agent_paths:
      - audio/2B_EricaM_output3.wav
      - audio/2B_EricaBF_output3.wav
      - audio/2B_EricaS_output3.wav
      - audio/2B_EricaZM_output3.wav
